### PR TITLE
HD-107991 [IGNIS] Disable languages except English and Spanish

### PR DESCRIPTION
**Pull request by wilbertverayin**
Remove all language folders except en and es.

The crypto app should now only have en and es as option for language

### CODE REVIEW

**Comment by cedricabuso** [comment]
I think we shouldn't delete them and just update the config on the selection dropdown on the client?

Since we'd probably want to support this still in the future

**Comment by wilbertverayin** [comment]
@pandafox suggested deleting it here
https://gitlab.com/mcnfreedom/vn-team/crypto/crypto.miner.client/-/merge_requests/307#note_340590176

Deleted languages can be retrieved on this diff
git diff 4b55996a 4a4e35

**Comment by cedricabuso** [comment]
@wilbertverayin I see, well, I guess we can just restore the files from previous commits anyway

**Review by cedricabuso — APPROVED** [review]

**Review by zsannenmariano — APPROVED** [review]

**Comment by pandafox** [comment]
@wilbertverayin please create a branch for that change so we can merge it back easily, thanks

**Review by pandafox — APPROVED** [review]

**Comment by wilbertverayin** [comment]
Added a PR for this.

https://github.com/anyTV/freedom-crypto-miner-i18n/pull/41

**Comment by jonelrempis** [comment]
QA Test Passed
- https://freedom.myjetbrains.com/youtrack/issue/HD-107991#focus=streamItem-99-103584.0-0

**Pull request merged**
